services:
  nzbhydra2:
    image: lscr.io/linuxserver/nzbhydra2:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - JAVA_OPTS=-Xms64m -Xmx256m
    ports:
      - 5076:5076
